title: store valves company
email: 
description: >- # this means to ignore newlines until "baseurl:"
 Welcome to  store valves company website
 our conpany is cell valves and you can allso fine knowledge about valves from this website
baseurl: "" # the subpath of your site, 
url: "" # the base hostname & protocol for your site, e.g. 
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
